# Generated by Django 3.0.5 on 2020-04-25 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_domain', models.CharField(max_length=255)),
                ('subdomain', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='BetaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('beta_key', models.UUIDField(blank=True, null=True)),
                ('num_links_allowed', models.PositiveSmallIntegerField(default=1)),
                ('num_sites_allowed', models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetaSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('beta_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BetaLink')),
                ('beta_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BetaUser')),
            ],
        ),
        migrations.AddField(
            model_name='betalink',
            name='beta_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BetaUser'),
        ),
        migrations.AlterUniqueTogether(
            name='betalink',
            unique_together={('base_domain', 'subdomain')},
        ),
    ]
