# Generated by Django 3.0.5 on 2020-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_links_allowed',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
