# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpcz.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpcz.proto',
  package='grpcz',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bgrpcz.proto\x12\x05grpcz\"1\n\x0cGRPCZRequest\x12\x13\n\x0bmodule_path\x18\x01 \x01(\t\x12\x0c\n\x04\x61rgs\x18\x02 \x03(\x0c\"(\n\rGRPCZResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x32=\n\x08\x44ispatch\x12\x31\n\x04\x63\x61ll\x12\x13.grpcz.GRPCZRequest\x1a\x14.grpcz.GRPCZResponseb\x06proto3'
)




_GRPCZREQUEST = _descriptor.Descriptor(
  name='GRPCZRequest',
  full_name='grpcz.GRPCZRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_path', full_name='grpcz.GRPCZRequest.module_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='grpcz.GRPCZRequest.args', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=71,
)


_GRPCZRESPONSE = _descriptor.Descriptor(
  name='GRPCZResponse',
  full_name='grpcz.GRPCZResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='grpcz.GRPCZResponse.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='grpcz.GRPCZResponse.msg', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['GRPCZRequest'] = _GRPCZREQUEST
DESCRIPTOR.message_types_by_name['GRPCZResponse'] = _GRPCZRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GRPCZRequest = _reflection.GeneratedProtocolMessageType('GRPCZRequest', (_message.Message,), {
  'DESCRIPTOR' : _GRPCZREQUEST,
  '__module__' : 'grpcz_pb2'
  # @@protoc_insertion_point(class_scope:grpcz.GRPCZRequest)
  })
_sym_db.RegisterMessage(GRPCZRequest)

GRPCZResponse = _reflection.GeneratedProtocolMessageType('GRPCZResponse', (_message.Message,), {
  'DESCRIPTOR' : _GRPCZRESPONSE,
  '__module__' : 'grpcz_pb2'
  # @@protoc_insertion_point(class_scope:grpcz.GRPCZResponse)
  })
_sym_db.RegisterMessage(GRPCZResponse)



_DISPATCH = _descriptor.ServiceDescriptor(
  name='Dispatch',
  full_name='grpcz.Dispatch',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=115,
  serialized_end=176,
  methods=[
  _descriptor.MethodDescriptor(
    name='call',
    full_name='grpcz.Dispatch.call',
    index=0,
    containing_service=None,
    input_type=_GRPCZREQUEST,
    output_type=_GRPCZRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISPATCH)

DESCRIPTOR.services_by_name['Dispatch'] = _DISPATCH

# @@protoc_insertion_point(module_scope)
