FROM decentralabs/noteworthy:DEV

ADD . /opt/noteworthy/dist
ADD install.sh /opt/noteworthy/
RUN chmod +x /opt/noteworthy/install.sh

RUN /opt/noteworthy/install.sh

ENTRYPOINT ["/usr/local/bin/notectl", "start"]