FROM decentralabs/noteworthy:latest

ADD . /opt/noteworthy/dist
ADD install.sh /opt/noteworthy/
RUN chmod +x /opt/noteworthy/install.sh

RUN /opt/noteworthy/install.sh

ENV NOTEWORTHY_ENV prod

ENTRYPOINT ["/usr/local/bin/notectl", "start"]