FROM decentralabs/noteworthy:latest

ADD . /opt/noteworthy/dist
# TODO fix messenger install hack
ADD messenger /opt/noteworthy/notectl/applications/messenger
ADD install.sh /opt/noteworthy/
RUN chmod +x /opt/noteworthy/install.sh

RUN /opt/noteworthy/install.sh

ENV NOTEWORTHY_ENV prod

ENTRYPOINT ["/usr/local/bin/notectl", "start"]