FROM decentralabs/noteworthy:DEV

ADD . /opt/noteworthy/dist
# TODO fix messenger install hack
ADD messenger /opt/noteworthy/notectl/applications/messenger
ADD riot_web /opt/noteworthy/notectl/plugins/riot_web
ADD install.sh /opt/noteworthy/
RUN chmod +x /opt/noteworthy/install.sh

RUN /opt/noteworthy/install.sh

ENV NOTEWORTHY_ENV dev

ENTRYPOINT ["/usr/local/bin/notectl", "start"]