# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='noteworthy_hub',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0emessages.proto\x12\x0enoteworthy_hub\"H\n\x12ReservationRequest\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0f\n\x07pub_key\x18\x02 \x01(\t\x12\x11\n\tauth_code\x18\x03 \x01(\t\"L\n\x13ReservationResponse\x12\x10\n\x08\x65ndpoint\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x15\n\rip_assignment\x18\x03 \x01(\tb\x06proto3'
)




_RESERVATIONREQUEST = _descriptor.Descriptor(
  name='ReservationRequest',
  full_name='noteworthy_hub.ReservationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='domain', full_name='noteworthy_hub.ReservationRequest.domain', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pub_key', full_name='noteworthy_hub.ReservationRequest.pub_key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_code', full_name='noteworthy_hub.ReservationRequest.auth_code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=106,
)


_RESERVATIONRESPONSE = _descriptor.Descriptor(
  name='ReservationResponse',
  full_name='noteworthy_hub.ReservationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='noteworthy_hub.ReservationResponse.endpoint', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='noteworthy_hub.ReservationResponse.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_assignment', full_name='noteworthy_hub.ReservationResponse.ip_assignment', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=184,
)

DESCRIPTOR.message_types_by_name['ReservationRequest'] = _RESERVATIONREQUEST
DESCRIPTOR.message_types_by_name['ReservationResponse'] = _RESERVATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReservationRequest = _reflection.GeneratedProtocolMessageType('ReservationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONREQUEST,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:noteworthy_hub.ReservationRequest)
  })
_sym_db.RegisterMessage(ReservationRequest)

ReservationResponse = _reflection.GeneratedProtocolMessageType('ReservationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONRESPONSE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:noteworthy_hub.ReservationResponse)
  })
_sym_db.RegisterMessage(ReservationResponse)


# @@protoc_insertion_point(module_scope)
