# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpcz import grpcz_pb2 as grpcz__pb2


class DispatchStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call = channel.unary_unary(
                '/grpcz.Dispatch/call',
                request_serializer=grpcz__pb2.GRPCZRequest.SerializeToString,
                response_deserializer=grpcz__pb2.GRPCZResponse.FromString,
                )


class DispatchServicer(object):
    """Missing associated documentation comment in .proto file"""

    def call(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call': grpc.unary_unary_rpc_method_handler(
                    servicer.call,
                    request_deserializer=grpcz__pb2.GRPCZRequest.FromString,
                    response_serializer=grpcz__pb2.GRPCZResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpcz.Dispatch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Dispatch(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpcz.Dispatch/call',
            grpcz__pb2.GRPCZRequest.SerializeToString,
            grpcz__pb2.GRPCZResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
